### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Gabriel-Koeller** [PokeAPI/pokedex#10]
Não consigo usar a API, a única que está funcionando é a do Ditto n°132 da pokedex, poís é o pokemon que aparece quando carrega a página, mas se mudar para qualquer outro da erro

**Comment by Naramsim** [comment]
> Não consigo usar a API, a única que está funcionando é a do Ditto n°132 da pokedex, poís é o pokemon que aparece quando carrega a página, mas se mudar para qualquer outro da erro
>
> I can't use the API, the only one that is working is that of Ditto n ° 132 from pokedex, because it is the pokemon that appears when loading the page, but moving to any other error

To use our API query it using this base URL: https://pokeapi.co/api/v2/

To get details about a pokemon: https://pokeapi.co/api/v2/pokemon/magikarp or https://pokeapi.co/api/v2/pokemon/1

A move: https://pokeapi.co/api/v2/move/guillotine

And so on...

**Comment by heitor582** [comment]
Search poke with id, some of them return undefined, for example the poke with id 513

**Comment by Naramsim** [comment]
https://pokeapi.co/api/v2/pokemon/513

What do you mean by "poke with id"?

**Comment by heitor582** [comment]
For me this links return not found

**Comment by Naramsim** [comment]
> For me this links return not found

Hmm, are you behind a proxy? Check that, I confirm you our API is working fine. Also, try to inspect the request and check for any headers.

**Comment by heitor582** [comment]
Idk why but in my pc it isn't working in opera browser but in another pc on google chrome and isomnia  app works
whatever thank u for trying help me

**Comment by Naramsim** [comment]
no problem. maybe its an issue related to an extension.
