### ISSUE TITLE
Pokemon #773 silvally

### ISSUE THREAD

**Issue by ice-bear-32** [PokeAPI/pokedex#105]
hey there! I found a mistake on silvally pokemon species page (https://pokeapi.co/api/v2/pokemon-species/silvally) silvally is a legendary pokemon and in the API, the is_legendary key has value "false" it should be "true" fix it please.

**Comment by Naramsim** [comment]
Thanks for reporting, I made the change. It will be integrate in some days

**Comment by ice-bear-32** [comment]
> Thanks for reporting, I made the change. It will be integrate in some days

You're welcome!
