### ISSUE TITLE
Koffing and Weezing are missing their Galarian forms?

### ISSUE THREAD

**Issue by Ratstail91** [PokeAPI/pokedex#11]
Either that or my scraping tool is crap.

I know it's crap, but how crap?

**Comment by Naramsim** [comment]
Right now all Galarian forms are missing from our database :(

Do you know if other pokemon in Galar have different/multiple forms?

**Comment by Ratstail91** [comment]
A quick google search said yes - https://bulbapedia.bulbagarden.net/wiki/Regional_form

There are also some pokemon that ONLY evolve in their galarian forms, such as Perrserker and Obstagoon. I'm not sure how to contribute these, as I only had a quick look at the CSVs.

**Comment by Ratstail91** [comment]
Oh, I thought Koffing had a galarian form, I was wrong.

**Comment by Naramsim** [comment]
Well, I'm going to close this issue.

If you'd like to contribute, you could add the variants to our CSV files. Basically what we've done for the alola forms is:

Create another pokemon (for example Grimer Alola https://pokeapi.co/api/v2/pokemon/10112/) and then link it to the Grimer Species https://pokeapi.co/api/v2/pokemon-species/88/ `.varieties` as a variety.
