### ISSUE TITLE
Gengar has wrong ability

### ISSUE THREAD

**Issue by Sneffel** [PokeAPI/pokedex#131]
[this ](https://pokemondb.net/pokedex/gengar#dex-basics)says that Gengar has Cursed Body 

[this](https://pokeapi.co/api/v2/pokemon/gengar/), too
But everyone who's actually played the game knows it's actually [Levitate](https://www.smogon.com/dex/xy/pokemon/gengar/)

**Comment by twillia7** [comment]
Levitate was the ability from generations 3-6 (see [here](https://www.serebii.net/pokedex-xy/094.shtml)), but starting in generation 7 (see [here](https://www.serebii.net/pokedex-sm/094.shtml)), the ability was changed to Cursed Body. Not sure if there is currently a way to see abilities by generation but would be a nice addition if not.

Also, this is [Pokédex entry from Pokémon](https://www.pokemon.com/us/pokedex/gengar)

**Comment by Sneffel** [comment]
This is a bad design choice. Idgaf about gen 7

**Comment by merfed** [comment]
Gengar only has Levitate from generations III-VI. From generation VII onward it has Cursed Body. Your information is incorrect, and while you _might_ not care about generation VII you do seem to care at least about generations III-VI.

That said, I'm not aware of anything that handles changes in abilities through generations. So this will have to be added to correct this inaccurate data.

But so long as you do care about the most recent generations ability being correct, then the information provided by PokeAPI is correct.
