### ISSUE TITLE
Pokemon image not loading

### ISSUE THREAD

**Issue by adarshM84** [PokeAPI/pokedex#133]
Pokemon image is not loading.

**Comment by ADARSHSIDDHARTHSHANKARMISHRA** [comment]
Ok

**Comment by ADARSHSIDDHARTHSHANKARMISHRA** [comment]
Ok

**Comment by ADARSHSIDDHARTHSHANKARMISHRA** [comment]
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/188.png

Unable to see image by using link some time show or some time not show
