### ISSUE TITLE
Both Api rest and graphql beta after pokemon 905 jump to 10001

### ISSUE THREAD

**Issue by pife00** [PokeAPI/pokedex#137]
hello 
First I might thank you guys for this API I am a newer coder and making a app using pokemon API I am learning a lot things,

After pokemon 905  there is no 906 nether 1000 2000 3000 jump to 10001 , if you looing for in the api Rest 907 will get no found:  https://pokeapi.co/api/v2/pokemon/907

"id": 905,
"name": "enamorus-incarnate"

in grapql beta:

 {
        "id": 905,
        "name": "enamorus-incarnate"
      },
      {
        "id": 10001,
        "name": "deoxys-attack"
      },
      {
        "id": 10002,
        "name": "deoxys-defense"
      },
      {
        "id": 10003,
        "name": "deoxys-speed"
      },
      {
        "id": 10004,
        "name": "wormadam-sandy"
      },

**Comment by Naramsim** [comment]
this is intended

**Comment by pife00** [comment]
> this is intended

this is intended, you mean, this is no a error, pokemon api want to keep things like this?, because in the future you will fill those spaces?

**Comment by Naramsim** [comment]
yes
