### ISSUE TITLE
The GraphQL API is down

### ISSUE THREAD

**Issue by joaovitorqueiroz** [PokeAPI/pokedex#139]
I was using the api until the early hours of 01/03/2023, but today I am not succeeding

https://beta.pokeapi.co/graphql/v1beta

![image](https://user-images.githubusercontent.com/58531490/210353963-024dc377-bb11-42ab-a444-2f2354140641.png)

**Comment by raphaeroo** [comment]
Now it's appearing that message: 
`SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON`

**Comment by Naramsim** [comment]
working on it

**Comment by Naramsim** [comment]
ok, it should work now

**Comment by joaovitorqueiroz** [comment]
Great, it's back, thanks 🙌🙌
