### ISSUE TITLE
pokemon Darmanitan does not exisit in API

### ISSUE THREAD

**Issue by SheetsC** [PokeAPI/pokedex#141]
the API is missing a gen 5 mon. please update!:)

**Comment by Naramsim** [comment]
Have you tried querying /pokemon-species ?

**Comment by EricBeaulieu** [comment]
you can search up as a pokedex number, so pokemon/555.
when you do it in this way it will return the default name which is darmanitan-standard.
if you look up "pokemon-species/555" or "pokemon-species/darmanitan" youll see theres a variations selection, if you select that youll see all of the names it has.
{ "darmanitan-standard", "darmanitan-zen", "darmanitan-galar-standard", "darmanitan-galar-zen" }
when i discovered this aspect it was definitely a game changer, hope that helps

**Comment by Naramsim** [comment]
No, the right way is to query: https://pokeapi.co/api/v2/pokemon-species/darmanitan
