### ISSUE TITLE
Missing Generation IX Pokemons in graphql 

### ISSUE THREAD

**Issue by felipermfalcao** [PokeAPI/pokedex#142]
I'm using graphql and in my query all pokemons only have up to 905. The next one is 1001 and it's a variation. Is that so, is the data still being entered or am I querying it wrong?

thank you!

**Comment by Naramsim** [comment]
I think we need to update the data there

**Comment by Naramsim** [comment]
I'll try

**Comment by Naramsim** [comment]
Hi, I updated the service and the data

I checked and data should be there :)

**Comment by felipermfalcao** [comment]
> Hi, I updated the service and the data
> 
> I checked and data should be there :)

Yes, I saw it now and the data is there!

Thank you very much!!!!
