### ISSUE TITLE
Uproar is missing max-turns data

### ISSUE THREAD

**Issue by PhilipArmstead** [PokeAPI/pokedex#143]
The move Uproar hits up to three turns (between two and five on generation 3/4) but this data isn't listed in the move's meta object.

**Comment by Naramsim** [comment]
could you help us fixing this?

**Comment by PhilipArmstead** [comment]
[Consider it done](https://github.com/PokeAPI/pokedex/pull/144). I wasn't sure if anything needed building after making these changes.
