### ISSUE TITLE
https://pokeapi.co/api/v2/pokemon/giratina returns 'Not Found'

### ISSUE THREAD

**Issue by t84** [PokeAPI/pokedex#155]

**Comment by Naramsim** [comment]
Use the pomemon-species endpoint

**Comment by t84** [comment]
That endpoint doesnt give stats, types, weight or height or artwork/sprite urls

**Comment by Naramsim** [comment]
Yep, you have to query that and then select the pokemon you want. There's different giratina with different stats

**Comment by t84** [comment]
So you cant just leave it as the normal one instead of me having to change my script for 1 or few more  pokemon

**Comment by Naramsim** [comment]
yep
