### ISSUE TITLE
No info for mimikyu and minior

### ISSUE THREAD

**Issue by TheButcherrr** [PokeAPI/pokedex#156]
There is no json info for the pokemon minior and mimikyu. I get an error: Error occurred: Expecting value: line 1 column 1 (char 0).
https://pokeapi.co/api/v2/pokemon/minior doesnt work but
https://pokeapi.co/api/v2/pokemon-species/minior does

**Comment by Naramsim** [comment]
[pokeapi.co/api/v2/pokemon-species/minior](https://pokeapi.co/api/v2/pokemon-species/minior) check out the varieties property.

**Comment by TheButcherrr** [comment]
@Naramsim but https://pokeapi.co/api/v2/pokemon-species/mimikyu doesnt have the height and doesnt hve weight

**Comment by Naramsim** [comment]
yeah, you have to make a subsequent call to get the other info
