### ISSUE TITLE
WHERE'S AEGISLASH???????

### ISSUE THREAD

**Issue by jrivest2** [PokeAPI/pokedex#16]

**Comment by Naramsim** [comment]
Here: https://pokeapi.co/api/v2/pokemon/681

Next time you can write you're issue title a little more decently. I'd suggest "Aegislash is missing"

**Comment by jrivest2** [comment]
I’m really sorry. I wasn’t trying to be mean or anything. It won’t happen again. From: Alessandro PezzèSent: Thursday, November 12, 2020 10:04 AMTo: PokeAPI/pokedexCc: Justin Rivest; AuthorSubject: Re: [PokeAPI/pokedex] WHERE'S AEGISLASH??????? (#16) Here: https://pokeapi.co/api/v2/pokemon/681Next time you can write you're issue title a little more decently. I'd suggest "Aegislash is missing"—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
