### ISSUE TITLE
All pokemons from ID 917 up to ID 1010, have the wrong name

### ISSUE THREAD

**Issue by Rekuiem84** [PokeAPI/pokedex#161]
For example, pokemon 1000 is officially Gholdengo however everything but the sprite is Tinkaton's data.
https://bulbapedia.bulbagarden.net/wiki/Gholdengo_(Pok%C3%A9mon)

**Comment by Rekuiem84** [comment]
From ID 917 up to ID 1010, every pokemon has the wrong name

**Comment by Naramsim** [comment]
Closing in favor of https://github.com/PokeAPI/pokeapi/issues/863#issuecomment-1497981739
