### ISSUE TITLE
Most pokemon from Gen 9 (Scarlet Violet) have their wrong Sprite

### ISSUE THREAD

**Issue by brendonbusker** [PokeAPI/pokedex#162]
Someone else has already said this but I want it to get more well know. 
images/national dex number messes up currently at Tarountula which should be #917 in the national dex, on PokeAPI it is #918 and from there the entire order is completely messed up.

**Comment by Naramsim** [comment]
Closing in favor of https://github.com/PokeAPI/pokeapi/issues/863#issuecomment-1497981739
