### ISSUE TITLE
Bug Tinkatink Wrong ID

### ISSUE THREAD

**Issue by Agikc** [PokeAPI/pokedex#163]
tinka's id is 1000

**Comment by Rekuiem84** [comment]
Tinkatink's ID is 957, Gholdengo is the 1000th pokemon
https://bulbapedia.bulbagarden.net/wiki/Tinkatink_(Pok%C3%A9mon)
https://bulbapedia.bulbagarden.net/wiki/Gholdengo_(Pok%C3%A9mon)

**Comment by Naramsim** [comment]
Closing in favor of https://github.com/PokeAPI/pokeapi/issues/863#issuecomment-1497981739
