### ISSUE TITLE
Duplicate move entries for Pound

### ISSUE THREAD

**Issue by Sunlis** [PokeAPI/pokedex#167]
`/move/1` and `/move/876` both return a resource for the move "Pound". Move 867 is incorrectly listed as being introduced in Gen 9, and has various pieces of incorrect/incomplete information (incomplete list of `learned_by_pokemon`, missing all contest fields, missing name translations, etc.)

**Comment by Naramsim** [comment]
Hi, are you familiar with our data? I think I have a fix: https://github.com/PokeAPI/pokeapi/pull/885

Could you review it?

**Comment by Naramsim** [comment]
I instructed a deploy here: https://staging.pokeapi.co/api/v2/move/876

In 1-2 hours you should see the changes

**Comment by Naramsim** [comment]
is it fixed?

**Comment by Sunlis** [comment]
Yes the data I'm seeing in staging looks correct 👍
