### ISSUE TITLE
Zacian, Zamazenta (both forms) and Cresselia's stats are incorrect as of Gen 9

### ISSUE THREAD

**Issue by trm2418** [PokeAPI/pokedex#174]
They were updated in Gen 9. The current stats on their pages are for Gen 8. Here are the changes: https://www.serebii.net/scarletviolet/updatedstats.shtml

**Comment by Naramsim** [comment]
Hi, could you update the wrong data in our CSV files?

**Comment by giginet** [comment]
This issue will be fixed on https://github.com/PokeAPI/pokeapi/pull/912.

This repository is obsoleted. Please see PokeAPI/pokeapi
