### ISSUE TITLE
API incorrectly shows Walking Wake learns fake-out

### ISSUE THREAD

**Issue by linnos** [PokeAPI/pokedex#175]
![image](https://github.com/PokeAPI/pokedex/assets/39270663/31151934-c2ee-456b-b381-429799728f63)
Walking Wake doesn't learn fake out though.

**Comment by Naramsim** [comment]
Hi can you fix it in our CSV?

**Comment by linnos** [comment]
> Hi can you fix it in our CSV?

Sounds good!
