### ISSUE TITLE
Replace the hyphen on the response objets to underscores

### ISSUE THREAD

**Issue by vicentcotaina** [PokeAPI/pokedex#178]
I'm currently developing a mobile app using the API. To do this I'm using FlutterFlow, my problem is that when I have to reference the properties that include the mentioned symbol I can't because FlutterFlow doesn't allow that symbol when I reference a JSON path.

**Comment by Naramsim** [comment]
Can you use a `[]` notation?

**Comment by vicentcotaina** [comment]
Yeah, I already archive it. Sorry to bother you.
