### ISSUE TITLE
getting Not found on pokemon endpoint

### ISSUE THREAD

**Issue by martintoz** [PokeAPI/pokedex#31]
Should receive Goldeen's info but getting Not found

**Comment by Naramsim** [comment]
Hi, yes, it's a problem related to Cloudflare that we don't know how to solve. Adding a trailing slash might solve your issue. Also, if you wait maximum 24 hours it should behave normally.

Another thing to point out, this issue is relative to your Cloudflare zone, for example in the EU we are not having right now this problem with Goldeen.

**Comment by martintoz** [comment]
Thanks for your answer. The trailing slash does solve it. I'm getting this problem in Spain by the way

**Comment by Naramsim** [comment]
Ah, alright, then I'm in Italy and it doesn't happen.

**Comment by Naramsim** [comment]
Is it still occurring?

**Comment by luke-riu** [comment]
I've been experiencing this on `generation/7/` today.

**Comment by martintoz** [comment]
> Is it still occurring?

working for me even without trailing slash

**Comment by luke-riu** [comment]
Is this a case of Cloudflare being too sensitive or something? I've made a pokedex app for my son that relies on this api, but only get's used a few times a day max. It kind of falls over when it hits a 404 like this

**Comment by Naramsim** [comment]
@luke-riu, we aren't sure where the error is occurring. We think it's on the Cloudflare side since it occurs in different zones.

**Comment by luke-riu** [comment]
ok. I'll maybe look putting in a generous cache on my api to try to mitigate this happening. 
Looking at the Cloudflare docs though, they're passing the blame.
https://support.cloudflare.com/hc/en-us/articles/115003014512#code_404

> Cloudflare does not generate 404s for customer websites, we only proxy the request on from the origin server. When seeing a 404 for your Cloudflare powered site you should contact your hosting provider for help.
