### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokedex#35]
Wouldnt it be easy to add a csv for languages? So we can have all the different names for pokemon?
Most of them can be fetched from for example pokewiki.de.

I dont know how to work with csv, but I would love to use the languages for my new website that I currently work on.

Greetz,

Luzifer

**Comment by Naramsim** [comment]
We already provide many different names in different languages. 

Check out https://pokeapi.co/api/v2/pokemon-species/1/. You find in the `.names[]` several languages.

**Comment by LuziferSenpai** [comment]
Oh sry, didnt see that! Thanks!
