### ISSUE TITLE
Some data will not work unless you remove '/' from the API provided link.

### ISSUE THREAD

**Issue by ToddGeorgeKelly** [PokeAPI/pokedex#41]
WILL work:
https://pokeapi.co/api/v2/pokemon/670 
https://pokeapi.co/api/v2/pokemon-species/143

Will NOT work:
https://pokeapi.co/api/v2/pokemon/670/ 
https://pokeapi.co/api/v2/pokemon-species/143/ 

Both of these links will not work with a '/' at the end, despite the API itself pointing to them while using a '/' at the end. 
Ideally, it should work with or without the forward slash at the end, just as nearly every other link on this API.

I have provided these two examples, I am not sure there are more yet.

**Comment by Naramsim** [comment]
Hi, thanks we are aware of this issue. We are working on solving it. 

It's about Cloudflare caches. It should resolve (and maybe re-present) in 24h.
