### ISSUE TITLE
Typo on Zamazenta's French name

### ISSUE THREAD

**Issue by polidano10** [PokeAPI/pokedex#42]
Hi! It seems that the French name for Zamazenta is wrong on https://pokeapi.co/api/v2/pokemon-species/889
It should be "Zamazenta", not "Zamazent"!
Have a nice day!
(English is not my native language, sorry in advance!)

**Comment by Naramsim** [comment]
Should be fixed, can you check?

**Comment by polidano10** [comment]
Yep, that's perfect! Thank you!
