### ISSUE TITLE
Ancient power raises the HP stat by one

### ISSUE THREAD

**Issue by LukeHackwell** [PokeAPI/pokedex#50]
The move "ancient-power" raises the HP stat by one. I don't think it's possible to raise HP by a stat change

**Comment by Naramsim** [comment]
Can you elaborate more？Do we provide incorrect information?

**Comment by simonorono** [comment]
Ancient power states that it increases HP by 1.

https://pokeapi.co/api/v2/move/ancient-power

However, this is not the case:

https://bulbapedia.bulbagarden.net/wiki/Ancient_Power_(move)#Effect

**Comment by Naramsim** [comment]
Our `flavor_text_entries` and `effect_entries` are taken straight from the ROMs themselves. We don't write those texts.

The very same website you linked reports our very same texts: https://bulbapedia.bulbagarden.net/wiki/Ancient_Power_(move)#Description

**Comment by Naramsim** [comment]
If you refer to the HP stat change in the property `.stat_changes` I'll look further and maybe submit a PR.

**Comment by simonorono** [comment]
Sorry for not being more specific. @Naramsim yes, I meant the HP stat change in `stat_changes`.

**Comment by Naramsim** [comment]
PR ready: https://github.com/PokeAPI/pokeapi/pull/627

**Comment by Naramsim** [comment]
Can you review it?
