### ISSUE TITLE
Incorrect Def stat on Ampharos for gens 1 through 4

### ISSUE THREAD

**Issue by brdy1** [PokeAPI/pokedex#51]
Ampharos had his defense stat increased between generations 4 and 5 and the API only returns the values for gen 5+. Is there a plan to account for stat changes between versions? 

These slight changes also apply to a couple dozen other Pokemon - they also had slight stat boosts in generation 5.

**Comment by Naramsim** [comment]
No, right now we don't have any plans to support older stats

**Comment by tttlumberjack** [comment]
Has the idea for adding this functionality ever been considered? Being able to reference stats specific to each generation would be very helpful for my situation.

**Comment by Naramsim** [comment]
Nope :(
