### ISSUE TITLE
net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by bretrca** [PokeAPI/pokedex#52]
https://pokeres.bastionbot.org/images/pokemon/{pokemon.id}.png not work

**Comment by Naramsim** [comment]
That's not our domain

**Comment by bretrca** [comment]
Yeah I saw a moment later, they use this page to show better images than the actual ones, but I have to re-read the documentation to use the correct one

**Comment by Naramsim** [comment]
No need for the docs

The image URLs are in the `sprites` property of the `pokemon` endpoint

https://pokeapi.co/api/v2/pokemon/bulbasaur
