### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by Makxspa** [PokeAPI/pokedex#59]
Hello, I have one question. You can change all the names from lowercase to uppercase, eg "charizard" -> "Charizard".
Same with us types.
It would be more aesthetic, especially since these are the names of the species.
Thank You

**Comment by Naramsim** [comment]
No, you can find uppercase names in the `pokemon-species` endpoint. There is a `names` property, you can filter out the language you need.

https://pokeapi.co/api/v2/pokemon-species/889
