### ISSUE TITLE
please correct name of Urshifu (Pókemon #892) in API

### ISSUE THREAD

**Issue by ow0x** [PokeAPI/pokedex#62]
Hi,

As per : https://pokeapi.co/api/v2/pokemon/892
currently pokeAPI returns Urshifu's name as `urshifu-single-strike` which doesn't make sense as a name of this pokemon, if I'm not wrong, it should be just `urshifu` instead (for ease of search and ease of accessibility to query pokeAPI for this pokemon) since on both Pokemon.com and bulbapedia, it is mentioned as just "Urshifu" to compare with official pokemon database references. 

1. https://www.pokemon.com/us/pokedex/urshifu
2. https://bulbapedia.bulbagarden.net/wiki/Urshifu_(Pok%C3%A9mon)

**Comment by Naramsim** [comment]
Please, check the `pokemon-species` endpoint.

https://pokeapi.co/api/v2/pokemon-species/892/

There you have the name and all translations.
