### ISSUE TITLE
version names are inconsistent between pokemon and items

### ISSUE THREAD

**Issue by ExperiBass** [PokeAPI/pokedex#67]
Hiya!

version names appear to be inconsistent between pokemon and items. for pokemon, the version will be something like `sword`. for items, it'll be `sword-shield`.

**Comment by Naramsim** [comment]
Can you post two examples? Two API calls?

**Comment by ExperiBass** [comment]
A typical entry for items/moves is this (using https://pokeapi.co/api/v2/move/roar):
```json
{
      "flavor_text": "Scares wild foes\nto end battle.",
      "language": {
        "name": "en",
        "url": "https://pokeapi.co/api/v2/language/9/"
      },
      "version_group": {
        "name": "gold-silver",
        "url": "https://pokeapi.co/api/v2/version-group/3/"
      }
    }
```
notice how `name` of `version_group` is `gold-silver`. For pokemon, the same version is (using https://pokeapi.co/api/v2/pokemon-species/ditto):
```json
{
    "flavor_text": "Its transformation\nability is per­\nfect. However, if\fmade to laugh, it\ncan't maintain its\ndisguise.",
    "language": {
        "name": "en",
        "url": "https://pokeapi.co/api/v2/language/9/"
    },
    "version": {
        "name": "silver",
        "url": "https://pokeapi.co/api/v2/version/5/"
    }
}```
now `name` is part of `version`, and its content is just `silver`.

**Comment by Naramsim** [comment]
Yeah, but those are two different things. `version` is different from `version-group`. A `version` belongs to a `version-group`.

**Comment by Naramsim** [comment]
I guess items/moves are specific to a `version-group` (ex: gold and silver). While a pokemon flavor text is tight only to specific versions. (ex: ponyta has a different flavor text in gold rather that fire-red)

**Comment by ExperiBass** [comment]
So that was on purpose? Alright, thanks!
