### ISSUE TITLE
rockruff is missing the ability Own Tempo

### ISSUE THREAD

**Issue by TeddyBearItsMe** [PokeAPI/pokedex#68]
https://pokeapi.co/api/v2/pokemon/744

**Comment by merfed** [comment]
[Rockruff Own Tempo](https://pokeapi.co/api/v2/pokemon/10151) is listed as a variety of [Rockruff](https://pokeapi.co/api/v2/pokemon-species/744).

**Comment by Naramsim** [comment]
@merfed thus this issue can be closed? Does only the own tempo variety have the own tempo ability?

**Comment by merfed** [comment]
[Rockruff Own Tempo](https://pokeapi.co/api/v2/pokemon/10151) does have the ability Own Tempo, and it's [base form ](https://pokeapi.co/api/v2/pokemon-species/744) has separate abilities.

Feel free to close, as the data is there, and represented correctly, even if it's not readily apparent to end-users how some of the data is presented (in this case, forms and varieties).
