### ISSUE TITLE
High Jump Kick flavour text

### ISSUE THREAD

**Issue by Glazelf** [PokeAPI/pokedex#71]
High Jump Kick data states:
`Inflicts regular damage. If this move misses, is blocked by protect or detect, or has no effect, the user takes half the damage it would have inflicted in recoil. This recoil damage will not exceed half the user's max HP. This move cannot be used while gravity is in effect.`

This has not been the case since gen 3. 
In gen 3 this holds true. The current implementation is that the user loses half of their max HP, rounded down. This has been the case since gen 5.

Source: https://bulbapedia.bulbagarden.net/wiki/High_Jump_Kick_(move)

**Comment by Naramsim** [comment]
Hi @Glazelf, thanks for reporting, can you link here the pokeapi call you analyzed?

**Comment by Glazelf** [comment]
Sure, @Naramsim.
Link: https://pokeapi.co/api/v2/move/high-jump-kick
Basically all the `effect_entries` seem to have this mistake.

**Comment by Naramsim** [comment]
Alright, we should now then update the `effect_changes[].effect_entries[].effect`. Would you like to subit a PR fixing it?

**Comment by Glazelf** [comment]
> Alright, we should now then update the `effect_changes[].effect_entries[].effect`. Would you like to subit a PR fixing it?

Sure I can do that.

**Comment by Glazelf** [comment]
![image](https://user-images.githubusercontent.com/35176230/144907938-9b665ae8-38f5-4889-9232-88714f0d8fe9.png)

Doesn't 629cc0130e73fa011d68b93a0212ee2f1fd25010 undo this commit and PR again?

**Comment by Naramsim** [comment]
Yep, sry for the mess
