### ISSUE TITLE
Mr. Rime Egg Groups Reporting Empty

### ISSUE THREAD

**Issue by JoshPCodes** [PokeAPI/pokedex#87]
Executing the Pokemon Species endpoint for Mr. Rime returns an empty list of egg groups. This seems to be incorrect, as Bulbapedia lists it as part of the Human-like (Humanshape) egg group.

To reproduce
1.  Execute the call "https://pokeapi.co/api/v2/pokemon-species/mr-rime"
2.  Check out the egg_groups attribute. It lists 0 entries.

Expectation: The egg_groups list would contain a single entry for "humanshape" 

![image](https://user-images.githubusercontent.com/98573089/151489362-f32884f4-386f-44a6-845e-de3003d9382d.png)

**Comment by Naramsim** [comment]
We probably lack that data. Would you be willing to contribute?

**Comment by JoshPCodes** [comment]
Hey Naramsim! Definitely not opposed to helping out with this if it isn't terribly taxing, time permitting. Would that require some level of db access? Or is the data updated in a different manner?

**Comment by Naramsim** [comment]
Hi, no, all the data is available as CSV files. It is here: https://github.com/PokeAPI/pokedex/tree/master-pokeapi/pokedex/data/csv

If you will contribute, I'd like to ask you to wait till this PR https://github.com/PokeAPI/pokedex/pull/86 is merged, otherwise you might have to fix conflicts

**Comment by JoshPCodes** [comment]
I took a quick scan before I asked, and somehow I missed that directory entirely. My mistake! Thank you for pointing me in the right direction!

It actually looks like PR 86 is adding the data I noticed was missing (added line 1110 in pokemon_egg_groups.csv), amongst its several other changes. If I encounter anything similar going forward, I'll see if I can contribute an update from my end.
